import '@rms-forge/ui-design-tokens/base.css';
import '@rms-forge/ui-design-tokens/font-loader.css';
import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'RMS Next App',
  description: 'Generated by rms-next-app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
